### ISSUE TITLE
Problems with the order in which code is run

### ISSUE THREAD

**Issue by laiyingxin2** [PeterGriffinJin/LMIndexer#1]
I'm sorry to bother you, I'm having problems, should I run through the Learn Semantic IDs process after downloading the data, when I run bash run_ours_retrieval_nq.sh directly from Downstream Tasks I'm encountering no Kmeans related files. Should I run that file first?

![Snipaste_2024-02-21_21-09-48](https://github.com/PeterGriffinJin/LMIndexer/assets/100742127/72fa1db6-7f98-40fa-8c4b-52da1551834a)

If I run Learn Semantic IDs first what should be the path where the data is stored, I notice that it's converted to json first.

**Comment by laiyingxin2** [comment]
downstream tasks and SemanticID seem to be in two different folders, do I need to manually migrate the files there?

**Comment by PeterGriffinJin** [comment]
Hi there,

I'm really sorry for my late reply. Yes, we need to run the learn semantic IDs process first. Then the learnt ID and semantic indexer can be used for downstream task tuning.

Please let me know if you have other questions.

Best,
Bowen
