### ISSUE TITLE
Question about downstream

### ISSUE THREAD

**Issue by laiyingxin2** [PeterGriffinJin/LMIndexer#3]
Hello,

In the paper, it is mentioned that the downstream tasks of the Lmindexer model are directly fine-tuned. However, in the files like LMIndexer/downstream/src/GEU/run_ours.py, I did not see any decoder structure; it only loads a pre-trained T5 model for training and prediction. It seems like there is no codebook or decoder. Could you please explain why this is the case? Is the T5 model alone sufficient for this purpose?

Thank you.

**Comment by laiyingxin2** [comment]
The scores 0.6480 and 0.8322 for the rq-VAE indexer in Table 6 of the paper—are they obtained by directly running LMIndexer/downstream/src/run_baseline_retrieval_qa.sh? If not, what is the specific setting or configuration corresponding to this baseline result?

![Uploading WX20240627-235908.png…]()

**Comment by laiyingxin2** [comment]
![Uploading WX20240627-235908.png…]()

**Comment by laiyingxin2** [comment]
![WX20240627-235908](https://github.com/PeterGriffinJin/LMIndexer/assets/100742127/80c46540-8f11-4169-aac5-a9582d8119f7)

**Comment by laiyingxin2** [comment]
![Snipaste_2024-06-28_14-55-44](https://github.com/PeterGriffinJin/LMIndexer/assets/100742127/722ce29f-82df-4f0b-800d-a3303578fbe8)

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you for your message.

During fine-tuning, the "reconstructor" is not needed and the codebook is integrated into the vocabulary embedding table of the language model indexer (which is the T5 model in our experiment). So, from the code itself, it will look like just loading a T5 model. But in fact, it is loading the LMIndexer together with the codebooks.

Yes, for results in Table 6, you can run ```run_baseline_retrieval_qa.sh``` for the NQ dataset and```run_baseline_retrieval_macro.sh``` for the macro dataset. For the baselines, you may need to first obtain the document embeddings from ```https://github.com/PeterGriffinJin/LMIndexer/tree/main/downstream/src/embedding```.

Best,
Bowen
